name: Bedwars
version: 1.0
author: Filiprogrammer
main: filip.bedwars.BedwarsPlugin
api-version: 1.13
softdepend: [Multiverse-Core]
commands:
  bw:
    description: Base command for all Bedwars commands
    usage: /<command>
    permission: filip.bedwars.base
  bw addarena:
    description: Add a new arena in the world you are currently in
    usage: /<command> [mapName] [minPlayersToStart] [maxPlayersPerTeam]
    permission: filip.bedwars.setup
  bw finisharena:
    description: Finish adding the new arena
    usage: /<command>
    permission: filip.bedwars.setup
  bw cancelarenasetup:
    description: Cancel adding the new arena
    usage: /<command>
    permission: filip.bedwars.setup
  bw reload:
    description: Reload the config files
    usage: /<command>
    permission: filip.bedwars.reload
  bw joingame:
    description: Join a game
    usage: /<command>
    permission: filip.bedwars.play.command
  bw setmainlobby:
    description: Set the main lobby
    usage: /<command>
    permission: filip.bedwars.setup
  bw setgamelobby:
    description: Set the game lobby
    usage: /<command>
    permission: filip.bedwars.setup
  bw removearena:
    description: Removes an arena
    usage: /<command> [mapName]
    permission: filip.bedwars.setup
  bw listarenas:
    description: List all arenas
    usage: /<command>
    permission: filip.bedwars.base
  bw leave:
    description: Leave a game
    usage: /<command>
    permission: filip.bedwars.play.command
  bw start:
    description: Skip the lobby countdown
    usage: /<command>
    permission: filip.bedwars.lobby.skip
permissions:
  filip.bedwars.base:
    description: hj
    default: true
  filip.bedwars.play.command:
    description: hj
    default: true
  filip.bedwars.play.sign:
    description: hj
    default: true
  filip.bedwars.setup:
    description: aho
    default: op
  filip.bedwars.reload:
    description: hablydably
    default: op
  filip.bedwars.lobby.skip:
    description: Skip the lobby countdown
    default: op
