# This only effects the language of the server console
language: en_us

main-lobby:
  w: world
  x: 0.0
  y: 65.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

game-lobby:
  w: world
  x: 0.0
  y: 65.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Game Lobby Countdown in seconds
game-lobby-countdown: 60

game-world-prefix: bw_game_

item-shop-name: '&2Item Shop'
team-shop-name: '&1Team Shop'
base-spawn-point-name: '&dSpawn-Point'

join-sign-line-one: '&a[BedWars]'
join-sign-line-two: '&d%arenaname%'
join-sign-line-three: ''
join-sign-line-four: '&b<Join Arena>'

lobby-bossbar: true
lobby-bossbar-color: YELLOW

# 0 to make the countdown unskippable
lobby-skip-countdown: 5

hunger: false
drop-only-spawner-resources-on-death: true
attack-cooldown: false
respawn-delay: 5
bedwars-chat: true
