# This only effects the language of the server console
language: en_us

main-lobby:
  w: world
  x: 0.0
  y: 65.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

game-lobby:
  w: world
  x: 0.0
  y: 65.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

game-world-prefix: bw_game_

hunger: false

item-shop-name: '&2Item Shop'
team-shop-name: '&1Team Shop'
base-spawn-point-name: '&dSpawn-Point'