name: Bedwars
version: 1.0
author: Filiprogrammer
main: filip.bedwars.BedwarsPlugin
api-version: 1.13
commands:
  bw:
    description: Base command for all Bedwars commands
    usage: /<command>
    permission: filip.bedwars.base
  bw addarena:
    description: Add a new arena in the world you are currently in
    usage: /<command> [mapName]
    permission: filip.bedwars.setup
  bw finisharena:
    description: Finish adding the new arena
    usage: /<command>
    permission: filip.bedwars.setup
  bw cancelarenasetup:
    description: Cancel adding the new arena
    usage: /<command>
    permission: filip.bedwars.setup
permissions:
  filip.bedwars.base:
    description: hj
    default: true
  filip.bedwars.setup:
    description: aho
    default: op